# Generated by Django 4.2.11 on 2024-11-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
