"""
Django settings for back project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'  # 클라이언트가 파일에 접근할 때 사용하는 URL
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(env_file=os.path.join(BASE_DIR, '.env'))
# API_KEY=env('API_KEY')
CHATBOT_API_KEY=env('chatbot_api_key')
FINLIFE_API_KEY=env('finlife_api_key')
EXCHANGE_API_KEY=env('exchange_api_key')
NAVER_CLIENT_ID=env('naver_client_id')
NAVER_CLIENT_SECRET=env('naver_client_secret')



# DEBUG = env.bool('DEBUG', default=False)
# Application definition

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c1s=k=s1j2k)_r&hh1p(x%9v-d@vyk9p_xuw5_1m)ntha4$n@b'

INSTALLED_APPS = [
    'chatbot',
    'finlife',
    'accounts',
    'article',
    'predict',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django.contrib.sites',        # 사이트 관리를 위한 앱
    'allauth',                     # django-allauth 메인 앱
    'allauth.account',             # 계정 관리를 위한 앱
    'allauth.socialaccount',       # 소셜 계정 연동을 위한 앱 (필요시)
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
]
SITE_ID=1
REST_FRAMEWORK={
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.AllowAny',
    ],
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:5173',
    'http://localhost:5173',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',  # Vue 개발 서버 주소
    'http://127.0.0.1:5173'   # 로컬 IP
]
CORS_ALLOW_CREDENTIALS = True  # 쿠키 전송을 허용

AUTH_USER_MODEL='accounts.User'
ROOT_URLCONF = 'back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back.wsgi.application'

ROOT_URLCONF = 'back.urls'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysql_db',
        'USER': 'root',
        'PASSWORD': '0000',
        'HOST': 'localhost',   # MySQL 호스트
        'PORT': '3306',        # MySQL 포트 (기본값은 3306)
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

PHONENUMBER_DEFAULT_FORMAT = 'NATIONAL' # Serializer Field 설정(Defulat=E164)
PHONENUMBER_DB_FORMAT = 'NATIONAL' 


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_AUTH = {
 'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
 'USER_DETAILS_SERIALIZER': 'accounts.serializers.CustomUserDetailsSerializer'
}

ACCOUNT_EMAIL_VERIFICATION = 'none'

# 세션 설정
SESSION_COOKIE_SAMESITE = 'Lax'  # 'Strict' 또는 'None' (HTTPS 사용 시)
SESSION_COOKIE_SECURE = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'article': {  # 'your_app_name'을 실제 앱 이름으로 변경
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

#비밀번호 찾기 용
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT='587'
EMAIL_HOST_USER='juha0824@gmail.com'
EMAIL_HOST_PASSWORD='xwae grfc qkaa gqqr'
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL=EMAIL_HOST_USER

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'  # 'Strict' 또는 'None' 필요 시 변경
