# Generated by Django 4.2.11 on 2024-11-24 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0002_investmentstyletype_userinvestmentstyle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.userinvestmentstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('TYPE', '투자 종류'), ('PRODUCT', '추천 상품'), ('RATIO', '투자 비율')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('ratio', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chatbot.portfolio')),
            ],
            options={
                'ordering': ['item_type', 'order'],
            },
        ),
    ]
